apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "FollowtheLider"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
 
locations:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
     - type: file
      target: ./apis/openapi-example.yaml
  
